SportsCenter/config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  resources :profiles
  devise_for :users
  get 'about/index'
  root 'home#index'

  get '/home', :controller=>'home', :action=>'index'
  get '/about', :controller=>'about', :action=>'index'
  get '/contact', :controller=>'contact', :action=>'index'
  get '/signedinuserprofile', :controller=>'profiles', :action=>'signedinuserprofile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SportsCenter/app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
end

SportsCenter/app/controllers/bookings_controller.rb
require 'calculateprice'

class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    if current_user.admin?

      if params[:search]
        @bookings = Booking.where('bookings.lot LIKE :name', {:name => "%#{params[:search]}%"})

        if @bookings.size == 0
          @bookings = Booking.all
        end
      else
        @bookings = Booking.all
      end
    else
      if params[:search]
        @bookings = Booking.where('bookings.lot LIKE :name AND bookings.user_id = :id', {:name => "%#{params[:search]}%", :id => current_user.id})

        if @bookings.size == 0
          @bookings = current_user.bookings.all
        end
      else
        @bookings = current_user.bookings.all
      end
    end
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)
    @booking.user_id = current_user.id

    @booking.price = CalculatePrice.calculate_price(@booking.lot, @booking.duration)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update

    @booking.price = CalculatePrice.calculate_price(@booking.lot, @booking.duration)

    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:lot, :price, :duration, :date)
    end
end

SportsCenter/app/helpers/bookings_helper.rb
module BookingsHelper
end

SportsCenter/app/views/bookings/_form.html.erb
<%= form_with(model: booking, local: true) do |form| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lot, class: "login_lbl" %>
    <%= form.select :lot, ['football', 'basketball', 'golf', 'tennis', 'squash', 'swimming pool', 'gym'] , class: "login_field", required: true %>
  </div>
  <!--
  <div class="field">
    <%= form.label :price, class: "login_lbl" %>
    <%= form.text_field :price, class: "login_field", required: true  %>
  </div>
  -->

  <div class="field">
    <%= form.label :duration, class: "login_lbl" %>
    <%= form.number_field :duration, class: "login_field", placeholder: "In Hours", min: 1, max: 4, required: true  %>
  </div>

  <div class="field">
    <%= form.label :date, class: "login_lbl" %>
    <%= form.datetime_select :date, class: "login_field" %>
  </div>

  <div class="actions">
    <%= form.submit class: "login_btn btn" %>
  </div>
<% end %>

SportsCenter/app/views/bookings/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to('SportsCenter', root_path, :class => "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to('Home', root_path, :class => "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('About', about_path, :class => "nav-link") %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if current_user.admin? %>
            <%= link_to('Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profiles', profiles_path, :class => "dropdown-item") %>
          <% else %>
            <%= link_to('My Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profile', profile_path(current_user.id), :class => "dropdown-item") %>
            <%= render 'devise/menu/registration_items' %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= render 'devise/menu/login_items' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="login_container">
    <div class="login_form">
      <h2 class="login_title">Edit Booking</h2>
      <div class="form_content">
        <%= render 'form', booking: @booking %>
      </div>
      <%= link_to 'Back to Booking', @booking, class: "btn login_btn" %>
    </div>
</div>

SportsCenter/app/views/bookings/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to('SportsCenter', root_path, :class => "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to('Home', root_path, :class => "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('About', about_path, :class => "nav-link") %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if current_user.admin? %>
            <%= link_to('Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profiles', profiles_path, :class => "dropdown-item") %>
          <% else %>
            <%= link_to('My Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profile', profile_path(current_user.id), :class => "dropdown-item") %>
            <%= render 'devise/menu/registration_items' %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= render 'devise/menu/login_items' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="booking_container">
  <div class="booking_table_wrapper">
    <h2 class="booking_title">Bookings</h2>
    <%= form_tag(bookings_path, :method => "get") do %>
      <%= text_field_tag :search, params[:search], class: '' %>
      <%= button_tag 'Search', name: nil, class: 'btn search_btn' %>
    <% end %>
    <div class="booking_content">
      <table class="booking_table">
        <thead>
          <tr>
            <th>Lot</th>
            <th>Price</th>
            <th>Duration</th>
            <th>Date</th>
            <th>User</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @bookings.each do |booking| %>
            <tr>
              <td><%= booking.lot %></td>
              <td><%= booking.price %></td>
              <td><%= booking.duration %></td>
              <td><%= booking.date %></td>
              <td><%= booking.user %></td>
              <td><%= link_to 'View', booking, class: "show_link" %></td>
              <td><%= link_to 'Edit', edit_booking_path(booking), class: "edit_link" %></td>
              <td><%= link_to 'Cancel', booking, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete_link" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="btn_content">
      <%= link_to 'New Booking', new_booking_path, class: "btn login_btn" %>
    </div>
  </div>
</div>

SportsCenter/app/views/bookings/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to('SportsCenter', root_path, :class => "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to('Home', root_path, :class => "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('About', about_path, :class => "nav-link") %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if current_user.admin? %>
            <%= link_to('Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profiles', profiles_path, :class => "dropdown-item") %>
          <% else %>
            <%= link_to('My Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profile', profile_path(current_user.id), :class => "dropdown-item") %>
            <%= render 'devise/menu/registration_items' %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= render 'devise/menu/login_items' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="login_container">
  <div class="login_form">
    <h2 class="login_title">Make a Booking</h2>
    <div class="form_content">
      <%= render 'form', booking: @booking %>
    </div>
    <% if current_user.admin? %>
      <%= link_to 'Back to all bookings', bookings_path %>
    <% else %>
      <%= link_to 'Back to my bookings', bookings_path %>
    <% end %>
  </div>
</div>

SportsCenter/app/views/bookings/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to('SportsCenter', root_path, :class => "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to('Home', root_path, :class => "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('About', about_path, :class => "nav-link") %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if current_user.admin? %>
            <%= link_to('Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profiles', profiles_path, :class => "dropdown-item") %>
          <% else %>
            <%= link_to('My Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profile', profile_path(current_user.id), :class => "dropdown-item") %>
            <%= render 'devise/menu/registration_items' %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= render 'devise/menu/login_items' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="login_container">
  <div class="login_form">
    <h4 class="login_title">Booking Info</h4>
    <div class="form_content view_booking">

      <p>
        <strong class="prolbl">Lot:</strong>
        <%= @booking.lot %>
      </p>

      <p>
        <strong class="prolbl">Price:</strong>
        <%= @booking.price %>
      </p>

      <p>
        <strong class="prolbl">Duration:</strong>
        <%= @booking.duration %>
      </p>

      <p>
        <strong class="prolbl">Date:</strong>
        <%= @booking.date %>
      </p>

      <p>
        <strong class="prolbl">User:</strong>
        <%= @booking.user %>
      </p>
    </div>
    <%= link_to 'Edit', edit_booking_path(@booking), class: "btn login_btn", id: "edit_booking" %>
    <% if current_user.admin? %>
      <%= link_to 'All Bookings', bookings_path, class: "btn login_btn" %>
    <% else %>
      <%= link_to 'My Bookings', bookings_path, class: "btn login_btn" %>
    <% end %>
  </div>
</div>