SportsCenter/config/routes.rb
Rails.application.routes.draw do

  resources :bookings
  resources :profiles
  devise_for :users
  get 'about/index'
  root 'home#index'

  get '/home', :controller=>'home', :action=>'index'
  get '/about', :controller=>'about', :action=>'index'
  get '/contact', :controller=>'contact', :action=>'index'
  get '/signedinuserprofile', :controller=>'profiles', :action=>'signedinuserprofile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SportsCenter/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

SportsCenter/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]


  def signedinuserprofile
    profile = Profile.find_by_user_id(current_user.id)
    if profile.nil?
      redirect_to "/profiles/new"
    else
      @profile = Profile.find_by_user_id(current_user.id)
      redirect_to "/profiles/#{@profile.id}"
    end
  end
  # GET /profiles
  # GET /profiles.json
  def index
    if current_user.admin?
      @profiles = Profile.all
    else
      redirect_to "/profiles/#{current_user.profile.id}"
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    respond_to do |format|
      format.html
      format.json {
        render json: @profile
      }
    end
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname)
    end
end

SportsCenter/app/helpers/profiles_helper.rb
module ProfilesHelper
end

SportsCenter/app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname, class: "login_lbl" %>
    <%= form.text_field :firstname, class: "login_field" %>
  </div>

  <div class="field">
    <%= form.label :lastname, class: "login_lbl" %>
    <%= form.text_field :lastname, class: "login_field" %>
  </div>



  <div class="actions">
    <%= form.submit class: "login_btn btn" %>
  </div>
<% end %>

SportsCenter/app/views/profiles/edit.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to('SportsCenter', root_path, :class => "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to('Home', root_path, :class => "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('About', about_path, :class => "nav-link") %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if current_user.admin? %>
            <%= link_to('Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profiles', profiles_path, :class => "dropdown-item") %>
          <% else %>
            <%= link_to('My Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profile', profile_path(current_user.id), :class => "dropdown-item") %>
            <%= render 'devise/menu/registration_items' %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= render 'devise/menu/login_items' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="login_container">
  <div class="login_form">
    <h2 class="login_title">Editing Profile</h2>
    <div class="form_content">
      <%= render 'form', profile: @profile %>
    </div>
    <%= link_to 'Back to Profile', @profile %>
  </div>
</div>

SportsCenter/app/views/profiles/index.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to('SportsCenter', root_path, :class => "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to('Home', root_path, :class => "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('About', about_path, :class => "nav-link") %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if current_user.admin? %>
            <%= link_to('Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profiles', profiles_path, :class => "dropdown-item") %>
          <% else %>
            <%= link_to('My Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profile', profile_path(current_user.id), :class => "dropdown-item") %>
            <%= render 'devise/menu/registration_items' %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= render 'devise/menu/login_items' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="profile_container">
  <div class="profile_table_wrapper">
    <h2 class="profile_title">Users</h2>
    <div class="profile_content">
      <table class="profile_table">
        <thead>
          <tr>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>User</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @profiles.each do |profile| %>
            <tr>
              <td><%= profile.firstname %></td>
              <td><%= profile.lastname %></td>
              <td><%= profile.user %></td>
              <td><%= link_to 'View', profile, class: "show_link" %></td>
              <td><%= link_to 'Edit', edit_profile_path(profile), class: "edit_link" %></td>
              <td><%= link_to 'Cancel', profile, method: :delete, data: { confirm: 'Are you sure?' }, class: "delete_link" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="btn_content">
      <%= link_to 'New Profile', new_profile_path, class: "btn login_btn" %>
    </div>
  </div>
</div>

SportsCenter/app/views/profiles/new.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to('SportsCenter', root_path, :class => "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to('Home', root_path, :class => "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('About', about_path, :class => "nav-link") %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if current_user.admin? %>
            <%= link_to('Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profiles', profiles_path, :class => "dropdown-item") %>
          <% else %>
            <%= link_to('My Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profile', profile_path(current_user.id), :class => "dropdown-item") %>
            <%= render 'devise/menu/registration_items' %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= render 'devise/menu/login_items' %>
        </div>
      </li>
    </ul>
  </div>
</nav>
<div class="login_container">
  <div class="login_form">
    <h3 class="login_title">Set Up Your New Profile</h3>
    <div class="form_content">
      <%= render 'form', profile: @profile %>
    </div>
  </div>
</div>

SportsCenter/app/views/profiles/show.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to('SportsCenter', root_path, :class => "navbar-brand") %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item">
        <%= link_to('Home', root_path, :class => "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('About', about_path, :class => "nav-link") %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if current_user.admin? %>
            <%= link_to('Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profiles', profiles_path, :class => "dropdown-item") %>
          <% else %>
            <%= link_to('My Bookings', bookings_path, :class => "dropdown-item") %>
            <%= link_to('Profile', profile_path(current_user.id), :class => "dropdown-item") %>
            <%= render 'devise/menu/registration_items' %>
          <% end %>
          <div class="dropdown-divider"></div>
          <%= render 'devise/menu/login_items' %>
        </div>
      </li>
    </ul>
  </div>
</nav>

<div class="login_container">
  <div class="login_form">
    <h5>You are Currently Logged in as:</h5>
    <div class="form_content">
      <p>
        <strong class="prolbl">Firstname:</strong>
        <%= @profile.firstname %>
      </p>
      <p>
        <strong class="prolbl">Lastname:</strong>
        <%= @profile.lastname %>
      </p>
    </div>
    <% if current_user.admin? %>
      <%= link_to 'View Bookings', bookings_path, class: "btn login_btn" %>
      <%= link_to 'View Profiles', profiles_path, class: "btn login_btn" %>
    <% else %>
      <%= link_to 'Edit', edit_profile_path(@profile), class: "btn login_btn" %>
    <% end %>
  </div>
</div>